### PR TITLE
Introduce connection flags

### PR DESCRIPTION
**Pull request by IvanUkhov**
See #16.

Two design choices have been considered:

```rust
// 1. a set of connection flags
let flags = ConnectionFlags::new().set_bla();
let connection = Connection::open_with_flags(path, flags);

// 2. a connection builder
let connection = ConnectionBuilder::new().set_bla().open(path);
```

I have decided for the former in order to avoid creating tension with the existing `set_` methods.

Any feedback is very much welcome.

### CODE REVIEW

**Comment by IvanUkhov** [comment]
One change that I’m considering is renaming `open_with_flags` to `new`. Not sure.

**Comment by nathansizemore** [comment]
That was fast. I didn't even get through my nap before this was up...

IMO, the builder pattern doesn't lend itself well to bitbanging flags, so I wouldn't recommend that approach. I also think there should be some "limitations" on what is allowed as far as flags go. Otherwise, you end up allowing this:

``` rust
use std::os::raw::c_int;

struct Foo(c_int);

fn main() {
    // Open with Goldeneye permissions
    let bar = Foo(007);
}
```

Generally, I think something like this will restrict people from placing in whatever thing they want, with things we know are possible:

``` rust
bitflags! {
    pub struct OpenOptions: i32 {
        const SQLITE_OPEN_READONLY      = ffi::FOO;
        const SQLITE_OPEN_READWRITE     = ffi::FOO;
        const SQLITE_OPEN_CREATE        = ffi::FOO;
        const SQLITE_OPEN_FULLMUTEX     = ffi::FOO;
        const SQLITE_OPEN_SHAREDCACHE   = ffi::FOO;
        const SQLITE_OPEN_PRIVATECACHE  = ffi::FOO;
        const SQLITE_OPEN_URI           = ffi::FOO;
    }
}
```

It's not perfect, but it restricts options to only things that SQLite is "currently" supporting.

**Comment by IvanUkhov** [comment]
In the current implementation, the inner field is private, and hence it is not possible to pass arbitrary flags without unsafe code. The only available options are

* `set_create`,
* `set_full_mutex`,
* `set_no_mutex`,
* `set_read_only`, and
* `set_read_write`.

In your example, you call it `OpenFlags`. I think it makes more sense than `ConnectionFlags`, and I have updated the code accordingly.

**Comment by IvanUkhov** [comment]
@999eagle, the read-only scenario becomes as follows:

```rust
let flags = OpenFlags::new().set_read_only();
let connection = Connection::open_with_flags(path, flags);
```

Any thoughts?

**Comment by nathansizemore** [comment]
Looks good to me.

**Comment by 999eagle** [comment]
Yep that looks good. Thank you for doing this so quickly :)

**Pull request merged**
